environment: development
port: 8080
company:
  mchId: df
  mchCertNo: ddd
  mchAPIv3Key: sss
  mchPrivateKey: ddd
apps:
  cns:
    appId: cns-appid
    appSecret: cns-app-secret
    appInternalID: 1
  rainbow:
    appId: rainbow-appid
    appSecret: rainbow-app-secret
    appInternalID: 2
inNotify: # 接受 微信官方支付服务 的通知
  wechat:
    payNotifyUrlBase: http://127.0.0.1:8080
    refundNotifyUrlBase: http://127.0.0.1:8080
    enable: true
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: conflux_pay_test
log:
  level: trace # trace,debug,info,warn,error,fatal,panic
  folder: /Users/dayong/myspace/mywork/conflux-pay/.log