company:
  mchId: df
  mchCertNo: ddd
  mchAPIv3Key: sss
  mchPrivateKey: ddd
apps:
  cns:
    appId: cns-appid
    appSecretHash: cns-app-secret-hash
    appInternalID: 1
  rainbow:
    appId: rainbow-appid
    appSecretHash: rainbow-app-secret-hash
    appInternalID: 2
order:
  notify_url_base: https://www.baidu.com/
